### ISSUE TITLE
Auth0 connection resource was deleted in the process of upgrading from v0.31.0 to v0.50.2 without any warnings

### ISSUE THREAD

**Issue by BhargavThakrar** [auth0/terraform-provider-auth0#914] opened 2024-01-26 18:55 UTC
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/terraform-provider-auth0/releases/latest) of this provider and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Auth0 connections were deleted without any warnings

### Expectation

The upgrade should have gone through successfully after making the necessary changes

### Reproduction

There are two main things deprecated in v0.50.2:
**1) The way we specify the connections for clients**
The enabled_clients argument has been completely removed from auth0_connection resource. So I had to move that enabled_clients to a new resource called [auth0_connection_clients](https://registry.terraform.io/providers/auth0/auth0/0.50.2/docs/resources/connection_clients). This has been changed for all the connections we support (google, apple, slack and auth0)

**2) The way we specify client credential authentication method**
The token_endpoint_auth_method argument is deprecated from [auth0_client](https://registry.terraform.io/providers/auth0/auth0/0.50.2/docs/resources/client#token_endpoint_auth_method) resource. We need to now use [auth0_client_credentials](https://registry.terraform.io/providers/auth0/auth0/0.50.2/docs/resources/client_credentials) resource to specify this

Of which there was no problem with point no 2, everything was fine there.

But for point no 1, the first terraform plan run complained about `fields_map` cannot be null even though I was not using it. And then I found that the data type of `fields_map` was changed and to support such breaking changes we should ideally remove and import the resource. This fixed the problem.

Then my plan showed nothing about the actual connections being destroyed and just mentioned that the `auth0_connection_clients` resource will be created. The first apply complained that the clients are already enabled for the connections, please import them. So I imported all the connections we had and than re-ran apply. This time it gave another error like this one:

`When applying changes to auth0_connection_clients.apple_clients_assoc[0], provider "registry.terraform.io/auth0/auth0" produced an unexpected new value: Root resource was present, but now absent`

And I just happen to see the auth0 dashboard and all my connections were already gone. What went wrong here?

### Auth0 Terraform Provider version

v0.50.2

### Terraform version

v0.13.6

**Comment by duedares-rvj** [comment] 2024-10-21 07:13
Hello @BhargavThakrar 
Apologies for such a late response on this. 

Is this still and issue for your team? Or have you moved forward with a more recent version of the provider?
Looking forward to hearing back, and will certainly provide sooner responses.

**Comment by duedares-rvj** [comment] 2024-11-14 17:30
Circling back on it.

**Comment by duedares-rvj** [comment] 2024-12-20 05:41
Hello Brargav,
Since there has not been much activity here, I'm going ahead and closing this issue for now.
Please feel free to re-open this or create a new issue describing your issue with steps to reproduce.

Thanks!

**Closed by duedares-rvj** 2024-12-20 05:41 UTC
Labels: :beetle: bug
