### ISSUE TITLE
Error while importing auth0_trigger_actions

### ISSUE THREAD

**Issue by snocorp** [auth0/terraform-provider-auth0#806] opened 2023-09-01 13:58 UTC
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/terraform-provider-auth0/releases/latest) of this provider and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

After updating the provider from 0.50 to 1.0.0-beta.2, I was following the migration guide and importing the auth0_trigger_actions resources and got an error like the following

```
Error: Invalid resource instance data in state
...
data could not be decoded from the state: unsupported attribute "client_secret"
```

I believe that this indicates I need to remove all auth0_client resources from the state and then import them as well but the migration guide doesn't give any instructions to do that so I might be incorrect.

### Expectation

I expected this to work as the migration guide did not indicate that the state of the client would be incompatible after the upgrade. Alternatively, the [Reading Client Secret](https://github.com/auth0/terraform-provider-auth0/blob/main/MIGRATION_GUIDE.md#reading-client-secret) section of the migration should provide instructions similar to what is provided for the [Trigger Bindings](https://github.com/auth0/terraform-provider-auth0/blob/main/MIGRATION_GUIDE.md#trigger-bindings) section.

### Reproduction

1. Given a terraform state with one or more auth0_client resources
2. When I import `auth0_trigger_actions` into the state
3. I expect it to import without errors.

### Auth0 Terraform Provider version

1.0.0-beta.2

### Terraform version

1.0.5

**Comment by sergiught** [comment] 2023-09-04 09:28
Hey @snocorp 👋🏻 

Thanks for raising this issue with us. Unfortunately I wasn't able to reproduce the issue, I created a client and trigger actions with 0.50.0 and then upgraded to v1.0.0-beta.2 and did a terraform refresh and the operation was successful. I tried this with both terraform v1.0.5 and the latest version. 

Can I ask you to please provide a minimal sample reproducible and the exact steps, as I might be missing something specific, maybe you're referencing the `client_secret` from the `auth0_client` somewhere in you config? 🙏🏻

**Comment by snocorp** [comment] 2023-09-06 01:03
@sergiught I tested this theory by removing all references to client_secret from a resource and switching it to use the data source instead. It still has the same error when running the import.  I will attempt to create a minimal sample to see if I can reproduce it there.

**Comment by sergiught** [comment] 2023-09-18 09:58
Hey @snocorp 👋🏻 

I tried again to reproduce your issue, just focusing on a couple of `auth0_client` resources.

While on `0.50.0` I created 2 clients and referenced their respective `client_secret` attribute both from the resource and from the data source. 

```terraform
terraform {
  required_providers {
    auth0 = {
      source  = "auth0/auth0"
      version = "0.50.0"
    }
  }
}

provider "auth0" { }

resource "auth0_client" "my_client_1" {
  name = "Application Test 1"
  app_type = "non_interactive"
}

resource "auth0_client" "my_client_2" {
  name = "Application Test 2"
  app_type = "non_interactive"
}

data "auth0_client" "my_client_1" {
  client_id = auth0_client.my_client_1.id
}

data "auth0_client" "my_client_2" {
  client_id = auth0_client.my_client_2.id
}

output "secret_data" {
  sensitive = true
  value = [data.auth0_client.my_client_1.client_secret, data.auth0_client.my_client_2.client_secret, auth0_client.my_client_1.client_secret, auth0_client.my_client_2.client_secret]
}
```

And then I upgraded the provider to `1.0.0-beta.4` and removed the `auth0_client.client_secret` references and kept only the ones from the data sources. After a tf apply I got `Apply complete! Resources: 0 added, 0 changed, 0 destroyed.`. 

I would suggest to try upgrading your terraform version to the latest (currently **v1.5.7**) and try again.

As we haven't got any other issues similar to this one and we couldn't reproduce it, we'll be closing the issue down. However if you're able to provide us with a reproducible we can always reopen this. 

Thanks!

**Closed by sergiught** 2023-09-18 09:58 UTC
Labels: :beetle: bug
