### ISSUE TITLE
`auth0_client` not updating application after apply

### ISSUE THREAD

**Issue by patrickwilliamconway** [auth0/terraform-provider-auth0#773] opened 2023-08-10 17:04 UTC
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/terraform-provider-auth0/releases/latest) of this provider and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

## Problem

When I do a terraform apply on the my `auth0_client`, it is not removing the fields that the plan describes. 
```hcl
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # module.main.module.query_service[0].auth0_client.application will be updated in-place
  ~ resource "auth0_client" "application" {
        id                                  = <omitted>
        name                                = <omitted>
      - organization_require_behavior       = "pre_login_prompt" -> null
      - organization_usage                  = "require" -> null
        # (26 unchanged attributes hidden)



        # (3 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.main.module.query_service[0].auth0_client.application: Modifying... [id=<omitted>]
module.main.module.query_service[0].auth0_client.application: Modifications complete after 0s [id=<omitted>]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```

But when I then check my state after apply, the values haven't changed:
```hcl
> terraform state show "module.main.module.query_service[0].auth0_client.application" | grep -A 1 "organization_require_behavior"

    organization_require_behavior       = "pre_login_prompt"
    organization_usage                  = "require"
```
and the changes are not reflected on the dashboard UI.

## Debugging
Running apply with TF_LOG=DEBUG yields:
```hcl
2023-08-10T12:48:42.728-0400 [WARN]  Provider "registry.terraform.io/auth0/auth0" produced an invalid plan for module.main.module.query_service[0].auth0_client.application, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .custom_login_page: planned value cty.StringVal("") for a non-computed attribute
      - .encryption_key: planned value cty.MapValEmpty(cty.String) for a non-computed attribute
      - .sso: planned value cty.False for a non-computed attribute
      - .allowed_origins: planned value cty.ListValEmpty(cty.String) for a non-computed attribute
      - .allowed_logout_urls: planned value cty.ListValEmpty(cty.String) for a non-computed attribute
      - .client_aliases: planned value cty.ListValEmpty(cty.String) for a non-computed attribute
      - .logo_uri: planned value cty.StringVal("") for a non-computed attribute
      - .form_template: planned value cty.StringVal("") for a non-computed attribute
      - .allowed_clients: planned value cty.ListValEmpty(cty.String) for a non-computed attribute
      - .oidc_backchannel_logout_urls: planned value cty.SetValEmpty(cty.String) for a non-computed attribute
      - .web_origins: planned value cty.ListValEmpty(cty.String) for a non-computed attribute
      - .cross_origin_auth: planned value cty.False for a non-computed attribute
      - .cross_origin_loc: planned value cty.StringVal("") for a non-computed attribute
      - .sso_disabled: planned value cty.False for a non-computed attribute
      - .addons[0].samlp[0].signature_algorithm: planned value cty.StringVal("rsa-sha1") for a non-computed attribute
      - .addons[0].samlp[0].typed_attributes: planned value cty.True for a non-computed attribute
      - .addons[0].samlp[0].digest_algorithm: planned value cty.StringVal("sha1") for a non-computed attribute
      - .addons[0].samlp[0].binding: planned value cty.StringVal("") for a non-computed attribute
      - .addons[0].samlp[0].authn_context_class_ref: planned value cty.StringVal("") for a non-computed attribute
      - .addons[0].samlp[0].create_upn_claim: planned value cty.True for a non-computed attribute
      - .addons[0].samlp[0].destination: planned value cty.StringVal("") for a non-computed attribute
      - .addons[0].samlp[0].lifetime_in_seconds: planned value cty.NumberIntVal(3600) for a non-computed attribute
      - .addons[0].samlp[0].map_unknown_claims_as_is: planned value cty.False for a non-computed attribute
      - .addons[0].samlp[0].passthrough_claims_with_no_mapping: planned value cty.True for a non-computed attribute
      - .addons[0].samlp[0].recipient: planned value cty.StringVal("") for a non-computed attribute
      - .addons[0].samlp[0].signing_cert: planned value cty.StringVal("") for a non-computed attribute
      - .jwt_configuration: block count in plan (1) disagrees with count in config (0)
      - .refresh_token: block count in plan (1) disagrees with count in config (0)
module.main.module.query_service[0].auth0_client.application: Modifying... [id=<omitted>]
2023-08-10T12:48:42.731-0400 [INFO]  Starting apply for module.main.module.query_service[0].auth0_client.application
2023-08-10T12:48:45.041-0400 [WARN]  Provider "module.main.provider[\"registry.terraform.io/auth0/auth0\"]" produced an unexpected new value for module.main.module.query_service[0].auth0_client.application, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .organization_require_behavior: was null, but now cty.StringVal("pre_login_prompt")
      - .organization_usage: was null, but now cty.StringVal("require")
module.main.module.query_service[0].auth0_client.application: Modifications complete after 2s [id=<omitted>]
```

In particular, I'm confused at this:
```hcl
    The following problems may be the cause of any confusing errors from downstream operations:
      - .organization_require_behavior: was null, but now cty.StringVal("pre_login_prompt")
      - .organization_usage: was null, but now cty.StringVal("require")
```

### Expectation

It should update according to the plan generated.

### Reproduction

This is reproduced consistently on terraform apply

### Auth0 Terraform Provider version

v1.0.0-beta.1

### Terraform version

Terraform v1.1.4 on darwin_arm64

**Comment by sergiught** [comment] 2023-08-10 17:53
Hey @patrickwilliamconway 👋🏻 

Thanks for taking the time to raise this with us. This is a duplicate of https://github.com/auth0/terraform-provider-auth0/issues/713, unfortunately once these values are set, they cannot be unset. Please check particularly this message: https://github.com/auth0/terraform-provider-auth0/issues/713#issuecomment-1635906576.

**Closed** 2023-08-10 18:40 UTC
Labels: :beetle: bug
