### ISSUE TITLE
How can I configure `Fixed Length of Access Token & Authorization Code` in auth0 Tenant Settings

### ISSUE THREAD

**Issue by zhaoyi0113** [auth0/terraform-provider-auth0#79] opened 2022-03-04 08:09 UTC
In `Tenant Settings` page, there is a configuration for `Fixed Length of Access Token & Authorization Code`. 

Like below screenshot, is there a way to update the configuration via this provider?

![image](https://user-images.githubusercontent.com/3355579/156724430-17e5b3af-ded6-495b-812b-9ed79505daf0.png)

**Comment by sergiughf** [comment] 2022-03-04 12:50
Hey @zhaoyi0113 , thanks for opening this issue. Unfortunately this is a feature not yet available within the provider. It needs to be added first within https://github.com/auth0/go-auth0 to be able to be used here.

**Comment by sergiughf** [comment] 2022-03-04 13:12
As this is a duplicate of https://github.com/auth0/terraform-provider-auth0/issues/50, I'll be closing this down in favour of that.

**Closed by sergiughf** 2022-03-04 13:12 UTC
Labels: enhancement

**Comment by zhaoyi0113** [comment] 2022-03-05 09:15
Thanks for your reply. If I manually enable it on auth0 console, then run this provider to update other configurations, will this configuration be overridden?

**Comment by sergiughf** [comment] 2022-03-05 13:05
@zhaoyi0113 The configuration for the migration flags will not get touched while using this provider. :)
