### ISSUE TITLE
auth0_connection google-oauth2 import fails if `Allowed Mobile Client IDs` is empty.

### ISSUE THREAD

**Issue by Aurelian-Shuttleworth** [auth0/terraform-provider-auth0#100] opened 2022-03-28 12:47 UTC
### Describe the problem

When running import on `auth0_connection` resources using `google-oauth2` the import will fail with the error `decoding response payload failed: json: cannot unmarshal string into Go struct field ConnectionOptionsGoogleOAuth2.allowed_audiences of type []interface {}` unless the field `Allowed Mobile Client IDs` is not empty. 

### What was the expected behaviour?

when running `terraform import auth0_connection.<name>  <id>` on a social `google-oauth2` resource it completes successfully regardless of `Allowed Mobile Client IDs`

### Reproduction

1. Create a `google-oauth2` social connection with no `Allowed Mobile Client IDs` set.
2. Import the auth0_connection.

### Temporary Solution

1. Set an arbitrary client id in the `Allowed Mobile Client IDs` section of the social connection in the auth0 ui.
2. Import the resource
3. Remove the `Allowed Mobile Client IDs` entry created in step 1.

### Environment

```
terraform version version
Terraform v0.15.5
on darwin_amd64
+ provider registry.terraform.io/alexkappa/auth0 v0.26.2
+ provider registry.terraform.io/hashicorp/random v3.1.2
+ provider registry.terraform.io/hashicorp/vault v3.4.0
```

**Comment by sergiughf** [comment] 2022-03-28 14:04
Hey @Aurelian-Shuttleworth  thanks for opening this issue. The provider uses [auth0/go-auth0](https://github.com/auth0/go-auth0) under the hood and unfortunately we can't set empty values on any fields currently. It's an issue we'll fix soon and is already tracked through https://github.com/auth0/terraform-provider-auth0/issues/14. I'll close this down and add it as another reference to that issue as this is a duplicate of that.

**Closed by sergiughf** 2022-03-28 14:04 UTC
Labels: bug
