### ISSUE TITLE
auth0_role_permissions - Root resource was present but now absent.

### ISSUE THREAD

**Issue by chadrsmith** [auth0/terraform-provider-auth0#769] opened 2023-08-01 21:38 UTC
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/terraform-provider-auth0/releases/latest) of this provider and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

After I had followed the migration [instructions for migrating](https://github.com/auth0/terraform-provider-auth0/blob/main/MIGRATION_GUIDE.md#role-permissions) to use the resource `auth0_role_permissions` instead of defining them within the role. Here is how the role permissions are defined:

```
locals {
  org_mgmt_root_role_permissions = [
    "get:roles",
    "get:all_users",
    "get:users",
    "create:users",
    "edit:users",
    "delete:users"
  ]
}

resource "auth0_role" "root_role" {
  name        = "Root User - (Managed by Terraform)"
}

resource "auth0_role_permissions" "root_role_permissions" {
  role_id = auth0_role.root_role.id
  dynamic "permissions" {
    for_each = local.org_mgmt_root_role_permissions
    content {
      name                       = permissions.value
      resource_server_identifier = var.org_mgmt_api_identifier
    }
  }
}
```

I started to get this error when trying to apply the changes:

```
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to
│ module.managed_roles.auth0_role_permissions.root_permissions, provider
│ "provider[\"registry.terraform.io/auth0/auth0\"]" produced an unexpected
│ new value: Root resource was present, but now absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
```

### Expectation

success

### Reproduction

1. create api resource `auth0_resource_server`
2. create scopes for the api `auth0_resource_server_scopes`
3. create role `auth0_role`
4. create role permissions `auth0_role_permissions`
5. run `terraform init`
6. run `terraform plan`
7. run `terraform apply`

### Auth0 Terraform Provider version

0.50.0

### Terraform version

1.4.0

**Comment by willvedd** [comment] 2023-08-01 21:59
Hi @chadrsmith, this issue is caused by temporarily redundant ways of managing role permissions in v0.47+. Also see: [related issue](https://github.com/auth0/terraform-provider-auth0/issues/416#issuecomment-1621971018)  In order to quell this error, you'll need to add a specific `lifecycle` block to your role definition to explicitly ignore changes to the `permission` attribute that are being made with your new role permissions resource. 

**Example:**

```terraform
resource "auth0_role" "root_role" {
  name        = "Root User - (Managed by Terraform)"
  lifecycle {
	ignore_changes = [ permissions ] 
  }
}
```



You were referencing the migration guide for v0.x=>v1.0 when you should be referencing[ the migration guide from v0.46=> v0.47
](https://github.com/auth0/terraform-provider-auth0/blob/main/MIGRATION_GUIDE.md#role-permissions-1). I can sympathize with your confusion here, we can look into making this clearer in the guide.

This is a good time to mention that we recently released a [beta for v1.0.0](https://github.com/auth0/terraform-provider-auth0/releases/tag/v1.0.0-beta.1) which includes a number of improvements and fixes. Notably, it will work with the configuration you have above, without the `lifecycle` block. We encourage you to try it out. 

Hope that helps!

**Comment by chadrsmith** [comment] 2023-08-01 22:32
@willvedd Thanks for the prompt response! I did the suggested change and made sure we were following the migration guide you linked. I am getting the same error

**Comment by sergiught** [comment] 2023-08-02 10:05
Hey @chadrsmith 👋🏻 

I was able to reproduce your issue with version `0.50.0` of the provider but not with the `v1.0.0-beta.1` version.

So to help unblock you there are 2 options:

- (Recommended) Migrate to the `v1.0.0-beta.1` version
- (Not recommended) Keep using the `v0.50.0` and use the `permissions` block within the `auth0_role` resource instead of the `auth0_role_permissions` resource to manage a role's permissions, but keep in mind you'll have to migrate away from this pattern whenever you'll be able to allocate time to upgrade to the v1.

**Comment by tadhglewis** [comment] 2023-08-04 02:26
We also ran into the same issue. Any ideas when v0.51.0 will be released?

**Comment by sergiught** [comment] 2023-08-04 07:51
Hey @tadhglewis 👋🏻 

The beta is already out and you can install it through:

```terraform
terraform {
  required_providers {
    auth0 = {
      source  = "auth0/auth0"
      version = "1.0.0-beta.1"
    }
  }
}

provider "auth0" { }
```

For the v1.0.0 GA we aim at releasing that at the end of August.

**Comment by fstamour** [comment] 2023-08-09 18:07
I got this issue today and switching to version 1.0.0-beta.1 did the trick. Thanks

**Comment by sergiught** [comment] 2023-09-05 16:03
Hey folks, considering this is fixed within the v1 beta and GA is on the horizon we'll be closing this issue down. Please make time to upgrade to the beta or prepare for the GA upgrade.

**Closed by sergiught** 2023-09-05 16:03 UTC
Labels: :beetle: bug
