### ISSUE TITLE
auth0_client custom_login_page management

### ISSUE THREAD

**Issue by nlarcher-talend** [auth0/terraform-provider-auth0#409] opened 2022-12-01 15:29 UTC
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/terraform-provider-auth0/releases/latest) of this provider and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Actually, in my company Terraform topology, we used on auth0_client custom_login_page capability. 
We want to remove it from our topology to manage it directly by Auth0 management API. 
When I remove this options custom_login_page and custom_login_page_on in my terraform topology, when I launch a plan, I show a login page removal. After apply my modification, when I launch a new plan, I always show my login page in terraform plan diff.

### Expectation

After apply, I won't see login page diff in my terraform plan

### Reproduction

1. Have a terraform topology auth0_client with custom_login_page and custom_login_page_on describe
2.  Apply this topology
3. Remove custom_login_page and custom_login_page_on in my auth0_client topology
4. Plan and show custom_login_page removal
5. Apply
6. Plan again and show custom_login_page  still exists

### Auth0 Terraform Provider version

0.40.0

### Terraform version

1.1.3

**Comment by sergiught** [comment] 2023-01-04 21:39
Hey @nlarcher-talend 👋🏻 ,

Apologies for the delay in getting back to you on this one. 

The issue you're experiencing is actually not a bug but desired terraform behavior. Whenever you're doing an out of bonds change it will always get reflected in the terraform plan to correctly inform you on the drift between what's within your Auth0 Infrastructure and your terraform config. 

However you always have the ability to ignore certain changes through the lifecycle meta attribute. 

Example:

```
resource "auth0_client" "client1" {
  name                       = "some name"
  app_type                   = "spa"
  callbacks                  = ["http://localhost:3000"]
  oidc_conformant            = true
  token_endpoint_auth_method = "none"

  jwt_configuration {
    alg = "RS256"
  }

  lifecycle {
    ignore_changes = [
      custom_login_page 
    ]
  }
}
```

The above will ignore any changes intercepted for the `custom_login_page` attribute. 

Please try this out and let us know if you encounter any issues with this approach. Closing this down but we can always reopen if needed.

**Closed by sergiught** 2023-01-04 21:39 UTC
Labels: bug
