### ISSUE TITLE
Terraform is not overwriting manual changes

### ISSUE THREAD

**Issue by rpf3** [auth0/terraform-provider-auth0#117] opened 2022-04-01 20:56 UTC
### Describe the problem

I have an Auth0 client resource created and managed with Terraform and was not setting the `web_origins` argument.  In testing a change, I was in the Auth0 web console and set a single URL in the web origins field.  Now every time I run an `apply` Terraform wants to update the client to the correct value of an empty list.  However after the apply the value is still visible on the web console.  I even tried manually setting `web_origins = []` and that didn't change the result.

### What was the expected behavior?

I expect the Terraform provider to overwrite any manual changes in the UI and update the client with the values in the code.

### Reproduction

1. Create an `auth0_client` resource with nothing set for `web_origins`
2. In the web console, add a value to the web origins and save
3. Run another Terraform apply and verify the change to remove the web origin
4. Verify in the web console the web origin value is still present

### Environment

Terraform 1.0.0
Auth0 Provider 0.28.0

**Comment by rpf3** [comment] 2022-04-01 21:26
This looks like it's actually already tracked by #14 but I'll let someone else verify and close.

**Comment by sergiughf** [comment] 2022-04-04 14:00
Hey @rpf3, thanks for opening this issue and indeed it's a duplicate of #14. We're aiming at tackling that very soon. We'll keep everyone posted:) 

For now I'll close this down and add it in the summary of #14.

**Closed by sergiughf** 2022-04-04 14:00 UTC
Labels: bug
