### ISSUE TITLE
Cannot specify an empty string for `from` and `subject` in `auth0_email_template` resource

### ISSUE THREAD

**Issue by tennashi** [auth0/terraform-provider-auth0#76] opened 2022-03-03 03:17 UTC
### Describe the problem
`PUT /api/v2/email-templates/{templateName}` API requires `from` and `subject` field, but allows empty string.

But Bad Request error is returned if `from` or `subject` is an empty string in the resource definition.

### What was the expected behavior?
The following resources can be applied.

```
resource "auth0_email_template" "verify_email" {
  template = "verify_email"
  enabled = false
  from = ""
  subject = ""
  syntax = "liquid"
  url_lifetime_in_seconds = 432000
  body = "some body"
}
```

### Reproduction
1. Write the following resource
```
resource "auth0_email_template" "verify_email" {
  template = "verify_email"
  enabled = false
  from = ""
  subject = ""
  syntax = "liquid"
  url_lifetime_in_seconds = 432000
  body = "some body"
}
```

2. `terraform apply`
3. The following error is output
```
Error: 400 Bad Request: Payload validation error: 'Missing required property: subject'. (also) Payload validation error: 'Missing required property: from'.
```

The following is the output with `TF_LOG=DEBUG`

```
2022-03-03T11:24:10.023+0900 [DEBUG] provider.terraform-provider-auth0_v0.27.1: 2022/03/03 11:24:10 [DEBUG] Template: {
2022-03-03T11:24:10.023+0900 [DEBUG] provider.terraform-provider-auth0_v0.27.1:   "template": "verify_email",
2022-03-03T11:24:10.023+0900 [DEBUG] provider.terraform-provider-auth0_v0.27.1:   "body": "some body",
2022-03-03T11:24:10.023+0900 [DEBUG] provider.terraform-provider-auth0_v0.27.1:   "syntax": "liquid",
2022-03-03T11:24:10.023+0900 [DEBUG] provider.terraform-provider-auth0_v0.27.1:   "urlLifetimeInSeconds": 432000,
2022-03-03T11:24:10.023+0900 [DEBUG] provider.terraform-provider-auth0_v0.27.1:   "enabled": false
2022-03-03T11:24:10.023+0900 [DEBUG] provider.terraform-provider-auth0_v0.27.1: }
```

### Environment
- auth0/terraform-auth0-provider v0.27.1

**Comment by sergiughf** [comment] 2022-03-04 12:54
Hey @tennashi , thanks for opening this issue. This however is a duplicate of https://github.com/auth0/terraform-provider-auth0/issues/14. We're aware of this but unfortunately the fix is not that straightforward to implement currently. We'll be looking more into this soon.

**Closed by sergiughf** 2022-03-04 12:54 UTC
Labels: bug
