### ISSUE TITLE
SMS Connection unable to set "from" property to null to allow the use of the "messagingServiceSid" property

### ISSUE THREAD

**Issue by dionfoster** [auth0/terraform-provider-auth0#805] opened 2023-09-01 01:39 UTC
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/terraform-provider-auth0/releases/latest) of this provider and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

We are attempting to configure the messagingServiceSid property for use with auth0, however, the "from" property cannot be set to "null".  The omission of the "from" property also results in an empty string ''.  Within the auth0 SMS connection user interface, there is a radio button group to select either "Use Messaging Service" or "Use from".

![image](https://github.com/auth0/terraform-provider-auth0/assets/1791402/3e1429f2-7c95-457f-a70c-e13260be4597)

### Expectation

Omission of the "from" property should default to "nil" or "null" and setting the "messagingServiceSid" property should select the "Use Messaging Service" option in the auth0 user interface.

### Reproduction

Given the following auth0.Connection constructor, "from" should result in "null" or "nil" but results in empty string:

```
new auth0.Connection(
        'Sms-Connection',
        {
            name: 'sms',
            isDomainConnection: false,
            options: {
                name: 'sms',
                totp: {
                    length: 6,
                    timeStep: 180,
                },
                syntax: 'md_with_macros',
                template: 'Your verification code is: @@password@@',
                twilioSid: smsProviderSettings.twilioSid,
                twilioToken: smsProviderSettings.twilioToken,
                messagingServiceSid: smsProviderSettings.messagingServiceSid,
                disableSignup: false,
                bruteForceProtection: true,
            },
            strategy: 'sms',
        },
        { protect: true }
    );
```

### Auth0 Terraform Provider version

v0.50.1

### Terraform version

unsure

**Comment by sergiught** [comment] 2023-09-05 09:25
Hey @dionfoster 👋🏻 

Thanks for raising this with us. The issue is caused by the underlying Go SDK we leverage, as it prevents us from sending those values as null. I have a fix for this in https://github.com/auth0/go-auth0/pull/275, as soon as it gets merged and released we'll bump the version and make this fix available within terraform as well. I'll post an update once that's done.

**Comment by sergiught** [comment] 2023-09-15 15:10
Hey @dionfoster  👋🏻

Wanted to let you know that we have addressed this issue in the latest beta release. Please give it a try, and if you come across any other issues, don't hesitate to reach out.

Changelog: https://github.com/auth0/terraform-provider-auth0/releases/tag/v1.0.0-beta.4
Terraform Registry Docs: https://registry.terraform.io/providers/auth0/auth0/1.0.0-beta.4

✌🏻

**Closed by sergiught** 2023-09-15 15:10 UTC
Labels: :beetle: bug
