### ISSUE TITLE
Provide sensible defaults appropriate for the various app types

### ISSUE THREAD

**Issue by kidpollo** [auth0/terraform-provider-auth0#545] opened 2023-03-25 20:17 UTC
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/terraform-provider-auth0/releases/latest) of this provider and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I discovered this after creating a new app in new tenant using terraform. The logins would just not work. I found that the solution was to toggle the Native appp type and then it worked. THis is the related issue https://github.com/auth0/react-native-auth0/issues/62

### Expectation

No need to toggle app type manually

### Reproduction

1 Given a client config like

resource "auth0_client" "frontone_client" {
  name = "Foo"
  app_type = "native"
  allowed_logout_urls = [
    "foo://${var.domain}/ios/foo/callback",
    "foo://${var.domain}/android/foo/callback"
  ]
  callbacks = [
    "foo://${var.domain}/ios/foo/callback",
    "foo://${var.domain}/android/foo/callback"
  ]
}

2 Then The resulting client will not work correctly until app type is toggled

### Auth0 Terraform Provider version

0.45.0

### Terraform version

1.3.9

**Comment by sergiught** [comment] 2023-05-02 07:49
Hey @kidpollo 👋🏻 

Apologies for the delay in getting back to you on this one. The issue you're experiencing is caused by not having specified the `token_endpoint_auth_method` property and having set it to `none`. Docs: https://registry.terraform.io/providers/auth0/auth0/latest/docs/resources/client#token_endpoint_auth_method. 

If you check the issue you've linked, in the last comment https://github.com/auth0/react-native-auth0/issues/62#issuecomment-705703627 it specifies the solution as well. 

So ultimately the settings you're configuring your client with are invalid. This is not an issue with the provider itself. 

This however raises the question whether we should enhance the client resource with some sensible defaults to offer an improved DX, as there are quite a few parameters other than just the `token_endpoint_auth_method` that should have certain values for the various type of applications in order for them to be functional and provide an effective login (e.g. `client_grants`, `jwt_configuration`, etc.)

I'll leave this issue open so we can review the default values for the client resource, but meanwhile I'll change this issue type to "feature" instead, to better convey the fact that this is not a bug, but user misconfiguration.

**Comment by kidpollo** [comment] 2023-05-02 17:58
Thanks for the feedback!

**Comment by sergiught** [comment] 2023-07-11 18:04
Through the recently introduced `auth0_client_credentials` resource we've aimed at providing some sensible defaults for the authentication method, based on app type, so what you've described in this issue shouldn't happen any more with regards to the `token_endpoint_auth_method`. Closing this now. 

Docs: https://registry.terraform.io/providers/auth0/auth0/latest/docs/resources/client_credentials

**Closed by sergiught** 2023-07-11 18:04 UTC
Labels: :seedling: feature
