### ISSUE TITLE
auth0_client organization arguments not reflected in client when removed from config

### ISSUE THREAD

**Issue by tb00-cloud** [auth0/terraform-provider-auth0#713] opened 2023-07-13 09:49 UTC
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/terraform-provider-auth0/releases/latest) of this provider and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

When deploying the auth0_client resource you can define the following arguments:

- organization_require_behavior
- organization_usage 

If you then remove these arguments, Terraform will succeed but the changes will not have reflected in Auth0. The next time you plan/apply you will see Terraform wants to apply the changes again. 

### Expectation

Removing these arguments from the resource should also remove the organization config in Auth0.

### Reproduction

1. Deploy the resource auth0_client and specify values for the two arguments.
2. Remove the two arguments and apply.
3. Apply or plan again and see the changes did not take effect.

### Auth0 Terraform Provider version

0.50.0

### Terraform version

v1.5.2

**Comment by willvedd** [comment] 2023-07-14 12:17
The `options.configuration` property is intentionally omitted from export because it becomes encrypted when stored; the Management API cannot return the unencrypted values thereafter. If you GET your connection via the API you'll see something like this:

```
"configuration": {
        "foo": "2.0$26efecff8162aff6c65696f034d4a8a1$b012dd920361da4c43f575a38c8e6695$0aae5717b1fc0a961eb79c90c9f2555d1dfb306d3d0c6dffc699ab53814ee9ba"
},
```

However, the `options.configuration` property _will_ update the connection on import. If it is important to continually update these values, I'd recommend implementing a uni-directional workflow, otherwise you'll need to continually reconcile on export.

One thing that we could potentially explore in the future is to replace encrypted values with a designated placeholder to show that configurations exist, it would help visualize these values but doesn't seem like it would enable your intention of exporting the unencrypted values.

Hope that clears things up!

**Comment by sergiught** [comment] 2023-07-14 13:59
Hey @tb00-cloud 👋🏻 

Thanks for taking the time to raise this with us. Those two properties are optional so if removed from the config a change will not get triggered as the API doesn't allow removing those fields. If attempting to set them as an empty string or null value you'll get:

```
// For null
"Payload validation error: 'Expected type string but found type null' on property organization_usage (Defines how to proceed during an authentication transaction with regards an organization. Can be `deny` (default), `allow` or `require`). (also) Payload validation error: 'Expected type string but found type null' on property organization_require_behavior (Defines how to proceed during an authentication transaction when `client.organization_usage: 'require'`. Can be `no_prompt` (default), `pre_login_prompt` or `post_login_prompt`. `post_login_prompt` requires `oidc_conformant: true`).",

// For ""
"Payload validation error: 'Invalid value \"{params[0]}\"' on property organization_usage (Defines how to proceed during an authentication transaction with regards an organization. Can be `deny` (default), `allow` or `require`). (also) Payload validation error: 'Invalid value \"{params[0]}\"' on property organization_require_behavior (Defines how to proceed during an authentication transaction when `client.organization_usage: 'require'`. Can be `no_prompt` (default), `pre_login_prompt` or `post_login_prompt`. `post_login_prompt` requires `oidc_conformant: true`).",
```

So once set, you'll need to have a valid value on them, `deny`, `allow` or `require` for `organization_usage` or `no_prompt`, `pre_login_prompt` or `post_login_prompt` on `organization_require_behavior`. 

Let me know if you have any other questions. 

Closing this tho as it's not a bug but intended behavior.

**Closed by sergiught** 2023-07-14 13:59 UTC
Labels: :beetle: bug

**Comment by tb00-cloud** [comment] 2023-07-14 14:10
Hey @sergiught - thanks for confirming this.

In that case from a usability perspective it may be worth changing the default value of these attributes from null to whatever the default actually is. Or making these mandatory.

**Comment by sergiught** [comment] 2023-07-14 15:33
Hey @tb00-cloud 👋🏻 appreciate the valuable feedback! We can definitely look into improving the experience for folks like yourself when using the `auth0_client` resource. 

This particular instance is a bit tricky tho, because of several reasons:
- When creating a client, we can create it without specifying those values so when fetching the details of the client through the API we won't have those properties set. Because of this it makes sense to keep those fields as optional.
- Once those fields are set either directly when creating the client or when updating it, they can't be unset in the API response, so that's when the validations for the available options kick in. Because of this forcing a default value on them on create seems a bit odd and unexpected for most users.

Happy to discuss further.
