### ISSUE TITLE
auth0_client_grant scopes false differences

### ISSUE THREAD

**Issue by bennesp** [auth0/terraform-provider-auth0#1037] opened 2024-10-01 09:02 UTC
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/terraform-provider-auth0/releases/latest) of this provider and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Sorting of the property `scopes` of resource `auth0_client_grant` is reporting in the plan a difference but it is very difficult to spot real differences because of the sorting.
In fact, the plan tells that some scopes will be removed and the same scopes will be added in different lines

Example of plan:
```terraform

  ~ resource "auth0_client_grant" "my_api" {
      ~ scopes    = [
          - "read:users",
          - "update:users",
          - "delete:users",
          + "create:clients",
          + "create:organization_connections",
          + "create:organization_member_roles",
          + "create:organization_members",
          + "create:organizations",
          + "create:resource_servers",
          + "create:role_members",
          + "create:roles",
          + "create:user_tickets",
            "create:users",
          - "read:users_app_metadata",
          - "update:users_app_metadata",
          - "delete:users_app_metadata",
            "create:users_app_metadata",
          - "create:user_tickets",
          - "read:clients",
          - "update:clients",
            "delete:clients",
          - "create:clients",
          - "read:client_keys",
          - "read:resource_servers",
          - "update:resource_servers",
          + "delete:organization_connections",
          + "delete:organization_member_roles",
          + "delete:organizations",
            "delete:resource_servers",
          - "create:resource_servers",
          - "read:logs",
          - "read:roles",
          - "create:roles",
          - "delete:roles",
          - "update:roles",
          - "create:role_members",
          - "read:role_members",
            "delete:role_members",
          + "delete:roles",
          + "delete:users",
          + "delete:users_app_metadata",
          + "read:client_credentials",
          + "read:client_keys",
          + "read:clients",
          + "read:logs",
          + "read:organization_member_roles",
            "read:organizations",
          - "update:organizations",
          - "create:organizations",
          - "delete:organizations",
          - "create:organization_members",
          - "create:organization_connections",
          + "read:resource_servers",
          + "read:role_members",
          + "read:roles",
          + "read:users",
          + "read:users_app_metadata",
          + "update:clients",
            "update:organization_connections",
          - "delete:organization_connections",
          - "create:organization_member_roles",
          - "read:organization_member_roles",
          - "delete:organization_member_roles",
          - "read:client_credentials",
          + "update:organizations",
          + "update:resource_servers",
          + "update:roles",
          + "update:users",
          + "update:users_app_metadata",
        ]
        # (2 unchanged attributes hidden)
    }
```

### Expectation

I would expect scopes to be a `set` and not a `list`, so that real differences would be far easier to spot and no false differences are reported

### Reproduction

1. Create a client
2. Assign some scopes from terraform and some scopes from the UI to the client using auth0_client_grant
3. Run terraform plan

### Auth0 Terraform Provider version

1.6.1

### Terraform version

1.8.0

**Comment by duedares-rvj** [comment] 2024-10-21 05:48
@bennesp Hello, hope you're well.

I'm trying to understand the steps to reproduce this. 
1. Create a client
2. Assign some scopes from terraform 
3. Assign some scopes from UI to the client using auth0_client_grant?  

Did you mean just assign some scope from UI? 
If so, you might have to import the state of the client since it has been updated externally (outside of terraform)

I'd be happy to connect and understand the issue that you're facing.
Thanks!

**Comment by duedares-rvj** [comment] 2024-11-14 17:26
Lovely!
Delighted to hear that you are no more facing the issue.
I'm going to close this issue for now, but do not hesitate to create a new one if it re-appears. 
We'd be happy to triage and assist you!

Thanks again!

**Closed by duedares-rvj** 2024-11-14 17:26 UTC
Labels: :beetle: bug
