### ISSUE TITLE
auth0_connection not updating the enabled clients

### ISSUE THREAD

**Issue by georg-ikegps** [auth0/terraform-provider-auth0#96] opened 2022-03-27 23:17 UTC
### Describe the problem

I would like to disable all clients for a given connection:

```
resource "auth0_connection" "google_oauth2" {
  name     = "google-oauth2"
  strategy = "google-oauth2"
  enabled_clients = []

  options {
    disable_signup = true
  }
}
```

After applying the plan all clients are still enabled in the web UI.

### What was the expected behavior?

All clients are disabled in the web UI.
Instead there are no changes in the UI.
Running the plan again will propose the same changes as before.

### Reproduction

```
provider "auth0" {
  domain        = var.auth0_domain
  client_id     = var.auth0_client_id.value
  client_secret = var.auth0_client_secret.value
  debug         = false
}

resource "auth0_connection" "google_oauth2" {
  name     = "google-oauth2"
  strategy = "google-oauth2"
  enabled_clients = []

  options {
    disable_signup = true
  }
}
```

### Environment
n/a

**Comment by sergiughf** [comment] 2022-03-28 10:21
Hey @georg-ikegps thanks for opening this issue. The provider uses [auth0/go-auth0](https://github.com/auth0/go-auth0) under the hood and unfortunately we can't set empty values on any fields currently. It's an issue we'll fix soon and is already tracked through https://github.com/auth0/terraform-provider-auth0/issues/14. I'll close this down and add it as another reference to that issue as this is a duplicate of that.

**Closed by sergiughf** 2022-03-28 10:21 UTC
Labels: bug
